// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj9UdMFbZb4SiM5HyoRqhU7VRnbNQRbMo',
    appId: '1:760351376695:web:addaea29dcb84eed5886b2',
    messagingSenderId: '760351376695',
    projectId: 'book-management-38737',
    authDomain: 'book-management-38737.firebaseapp.com',
    storageBucket: 'book-management-38737.firebasestorage.app',
    measurementId: 'G-96XG66PPJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEQueu_rlY8yamenpV4yeqxmkKR_Sw8_Q',
    appId: '1:760351376695:android:950dc73c99ab9dae5886b2',
    messagingSenderId: '760351376695',
    projectId: 'book-management-38737',
    storageBucket: 'book-management-38737.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU0j7TG7MFQUijtOX5ni3BR7gFplWWoTQ',
    appId: '1:760351376695:ios:a184a92339d0cc6e5886b2',
    messagingSenderId: '760351376695',
    projectId: 'book-management-38737',
    storageBucket: 'book-management-38737.firebasestorage.app',
    iosBundleId: 'com.example.bookManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU0j7TG7MFQUijtOX5ni3BR7gFplWWoTQ',
    appId: '1:760351376695:ios:a184a92339d0cc6e5886b2',
    messagingSenderId: '760351376695',
    projectId: 'book-management-38737',
    storageBucket: 'book-management-38737.firebasestorage.app',
    iosBundleId: 'com.example.bookManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj9UdMFbZb4SiM5HyoRqhU7VRnbNQRbMo',
    appId: '1:760351376695:web:d2d576473672116c5886b2',
    messagingSenderId: '760351376695',
    projectId: 'book-management-38737',
    authDomain: 'book-management-38737.firebaseapp.com',
    storageBucket: 'book-management-38737.firebasestorage.app',
    measurementId: 'G-6H6R5P6NQR',
  );
}
